<a href="https://colab.research.google.com/github/JacksonMajwega/CSE712/blob/main/Copy_of_JACK_MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

hlo = np.array([12, 45, 10, 4, 5])

print(arr)
print(np.__version__)

[12 45 10  4  5]
1.19.5


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) # array() is a numpy ndarray object. [1,2,3,4,5] is a list
print(arr)
print(type(arr)) # type() built-in Python function tells us the type of the object passed to it. So arr is a numpy.ndarray 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
hi = np.array((1,2,3,4,5,6)) # a turple however gives the same results
print (type(hi))
print(hi)


<class 'numpy.ndarray'>
[1 2 3 4 5 6]


0-

In [ ]:
import numpy as np
fy = np.array(42) // 0-D array
print(fy)

42


**1-D ARRAYS**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [ ]:
import numpy as np
ty =np.array([1,2,3,4,5,6])
print(ty)

[1 2 3 4 5 6]


**2-D ARRAYS**

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [ ]:
import numpy as np
tr = np.array([[1,2,3],[3,4,5]])
print("the array is:",tr)

the array is: [[1 2 3]
 [3 4 5]]


**3-D ARRAYS**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
import numpy as np
tut = np.array([[[1,2,3], [3,4,5]],[[1,2,3], [4,5,6]]])
print(tut)

[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]]]


**Check Number of Dimensions?**

In [ ]:
import numpy as np
b = np.array([[1,2,3,4,5,6],[11,11,12,13,14,15]])
c = np.array([[[2,4,4,6]]])
print(b.ndim) # theoutput will be number of dimensions

2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


**## NumPy Array Indexing/acessing array elements**

In [ ]:
import numpy as np
p = np.array([1,2,3,90,58,60,21,9,78,45,56])
print(p[0], p[3], p[10], p[7])
print(p[4] + p[7], p[8] - p[10])

1 90 56 9
67 22


**## Access 2-D Arrays**

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.



In [ ]:
import numpy as np

pp = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(pp[1, 2]) # printing the third element in the second dimension
print(pp[0, 2]) # printing the third element in the 1st dimension
print(pp[1, 0]) # printing the first element in the second dimension

8
3
6


**Access 3-D Arrays**

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
import numpy as np
t = np.array([[[1,2,3],[3,4,5]], [[77,8,9], [10,11,12]]])
print(t[0,1,2]) #printing the third element of the second array of the first dimension
print(t[1,0,1]) #printing the second element of the first array of the second dimension
print(t[1,0,0]) #printing the first element of the first array of the second dimension

5
8
77


**Negative Indexing**

Use negative indexing to access an array from the end.

In [ ]:
import numpy as np
gd = np.array([[1,2,2,4,5,6,7], [7,8,9,1,41,10,52]])
print(gd[1,-1])
print(gd[1,-2])
print(gd[0,-4])

52
10
4


**Slicing arrays**

Slicing in python means taking elements from one given index to another given index.

In [ ]:
import numpy as np
my = np.array([1,2,3,4,5,6])
print(my[1:5]) # will print elements from index[1] to element in index[4] but will exclude the element in the 5th index

[2 3 4 5]


In [ ]:
import numpy as np
my = np.array([1,2,3,4,5,6])
print(my[:5]) # will print elements from index[0] to element in index[4] but will exclude the element in the 5th index

[1 2 3 4 5]


In [ ]:
import numpy as np
my = np.array([1,2,3,4,5,6])
print(my[2:]) # will print all elements starting from an element in index[2]

[3 4 5 6]


**Return every other element from index 1 to index 5:**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 

[2 4]
